### ISSUE TITLE
Compilation and empty topic problems

### ISSUE THREAD

**Issue by NilaySener** [smartmicro/smartmicro_ros2_radars#15]
Hi, i am facing a few errors while running the package. 

- First, when i try to compile i get this error:
```
Starting >>> umrr_ros2_msgs
Starting >>> SensorSimulator
--- stderr: SensorSimulator
/usr/bin/ld: cannot find -lcom_lib
/usr/bin/ld: cannot find -losal
/usr/bin/ld: cannot find -lumrr11_t132_automotivev1.1.1_user_interface
/usr/bin/ld: cannot find -lumrr96_t153_automotivev1.2.1_user_interface
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/simulator.dir/build.make:84: simulator] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/simulator.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
---
Failed   <<< SensorSimulator [0.06s, exited with code 2]
Aborted  <<< umrr_ros2_msgs [2.40s]                               
                                
Summary: 0 packages finished [2.53s]
  1 package failed: SensorSimulator
  1 package aborted: umrr_ros2_msgs
  1 package had stderr output: SensorSimulator
  1 package not processed
```

   I remove the simulator file and it did not give any error while  building. Is this file neseccary to launch node? 

- Then, I run into another problem when I try to launch node. The topic is not visualized on the Rviz screen. When I listen to the topic from the terminal, no message appears in it. I configure the ` radar.template.yaml` file like this:
```
---
/**:
  ros__parameters:
    # The client_id to be set in smart_access_config.json, must be a unique integer.
      master_client_id: 1
      # This sets the dev_id in the hw_inventory.json
      hw_dev_id: 2
      # This sets the port in the hw_inventory.json
      hw_port: 55555
      # This sets the iface_name in the hw_inventory.json
      hw_iface_name: "enp46s0"
      # An array of sensors to subscribe to.
      sensors:
          # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
          # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
          sensor_0:
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 100
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.17"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10

```
When I launch the node, there is no error in the terminal:
```
ros2 launch umrr_ros2_driver radar_rviz.launch.py 
[INFO] [launch]: All log files can be found below /home/nilay/.ros/log/2022-09-13-16-21-37-764950-nilay-40151
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [smartmicro_radar_node_exe-1]: process started with pid [40153]
[INFO] [rviz2-2]: process started with pid [40155]
[rviz2-2] [INFO] [1663075298.036421287] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1663075298.036529534] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-2] [INFO] [1663075298.052637901] [rviz2]: Stereo is NOT SUPPORTED
[smartmicro_radar_node_exe-1] [INFO] [1663075299.831572927] [smartmicro_radar_node]: Radar services are ready.
```
Do you think there is an error in the parameters in the .yaml file? I would be very grateful if you could help, thank you.
