### ISSUE TITLE
arm64 Support

### ISSUE THREAD

**Issue by JWhitleyWork** [smartmicro/smartmicro_ros2_radars#2]
The release of Smart Access provided with the driver is built for `amd64`. Is it possible to add the libraries for `arm64` support to the driver and have CMake link to the appropriate ones based on detected architecture?

**Comment by smartSRA** [comment]
> The release of Smart Access provided with the driver is built for `amd64`. Is it possible to add the libraries for `arm64` support to the driver and have CMake link to the appropriate ones based on detected architecture?

The current Smart Access doesn't provide support for `arm64`, however in the newer versions we do offer such support. It is planned to adopt the driver to include the new Smart Access version.

**Comment by JWhitleyWork** [comment]
@smartSRA Is there an expected release date for this new version? Will it work with this existing ROS2 driver or will modifications need to be made? My client needs this as soon as possible for a technology demonstration.

**Comment by smartSRA** [comment]
@JWhitleyWork There isn't a release date yet. With the newer smart access, modifications would need to be made to the driver.
As this would be a major update than.

However, I will try and see if we can provide arm64 support for the current version that the driver is using and get back to you.

**Comment by JWhitleyWork** [comment]
@smartSRA Thank you!

**Comment by smartSRA** [comment]
@JWhitleyWork Unfortunately this would not be possible for the current version.

**Comment by JWhitleyWork** [comment]
That is unfortunate. Is there any particular reason why this couldn't be built for `arm64` hardware?

**Comment by smartSRA** [comment]
We have a new pipeline for the newer version and all platforms supports are to be the features of the upcoming version. The pipeline for smart access v3xx has been discontinued and it was not intended to be run on `arm64` as there was no such requirements. 

I have already taken your request into account and this is also the first request for an `arm64` support so we have it now in our feature list. As soon as we get the arm64 support for smart access, I will update/release the newer version of the driver which would than have the arm64 support. However, this is going to take some time.

**Comment by JWhitleyWork** [comment]
Thank you for the information. My client has `arm64` hardware and three UMRR-96 Type 153 radars so let me know if we can be of any help with testing.

**Comment by AllanGErnst** [comment]
> We have a new pipeline for the newer version and all platforms supports are to be the features of the upcoming version. The pipeline for smart access v3xx has been discontinued and it was not intended to be run on `arm64` as there was no such requirements.
> 
> I have already taken your request into account and this is also the first request for an `arm64` support so we have it now in our feature list. As soon as we get the arm64 support for smart access, I will update/release the newer version of the driver which would than have the arm64 support. However, this is going to take some time.

We also have UMRR-96 Type 153 radars and arm64 hardware, and are quite desperate to get the umrr_ros2_driver up and running in ROS2 Foxy. Please let us know if there's anything we can do to help and accelerate this.

**Comment by smartSRA** [comment]
I have already started updating the driver to include the new smart access v4 and I will create an issue to track this.

**Comment by JWhitleyWork** [comment]
@smartSRA Thank you!

**Comment by smartSRA** [comment]
The new update of the driver provides the smart access arm libs. Readme mentions how to use them. It is possible to build and run the driver on an arm machine. I have tested it out on a raspberry pi 4. 

Cross building not offered yet and would be included in the next minor release.

**Comment by rsanchezm98** [comment]
@smartSRA I have tried the drivers on jetson agx xavier with ubuntu 18 [changing ros2 foxy to ros2 dashing staff] and it can compile, initialize the node, but callback of the data is never called. I checked in wireshark and data is being received perfectly. 

I tried to compile with armv8-gcc_9 but an error was thrown: 
lib-linux-armv8-gcc_9/libumrr11_t132_automotive1.1.1_user_interface.so: undefined reference to 'pow@GLIBC_2.29' [i tried adding -lm on the cmakelists on target_link_libraries but no succeed]

I checked my gcc version 9.4.0 so it should have been able to compile succesfully]. I compiled succesfully with armv8-gcc_7. But then I do not get data as I mentioned before. I do not know if it is yet compatible for jetson agx xavier...

**Comment by smartSRA** [comment]
@rsanchezm98 As you mentioned that you have complied successfully using the armv8-gcc_7 libs, it means there are no compatibility issues. 

I would assume that the driver has not been correctly configured.
Could you share your configs and also the syslogs?

**Comment by rsanchezm98** [comment]
There are no errors produced and syslog emitted when launching the node. I checked the subscription and publisher creation and they were correctly done. It goes waiting for receiving data [I put a comment and it never gets to the callback]. I see data is being sent to my jetson as I see on wireshark but the node does not do anything. I am able to ping the radar as well. 

This is my config file:
```yaml
---
/**:
  ros__parameters:
    # The client_id to be set in smart_access_config.json, must be a unique integer.
      master_client_id: 1
      # This sets the dev_id in the hw_inventory.json
      hw_dev_id: 2
      # This sets the port in the hw_inventory.json
      hw_port: 55555
      # This sets the iface_name in the hw_inventory.json
      hw_iface_name: "eth0"
      # An array of sensors to subscribe to.
      sensors:
          # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
          # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
          sensor_0:
              # The model of the connected sensor.
              model: "umrr11"
              # The client_id of the sensor/source, must be a unique integer.
              id: 100
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.25"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 1
```
