### ISSUE TITLE
No message published to /smart_radar/targets_0 for DRVEGRD 152

### ISSUE THREAD

**Issue by MBagory** [smartmicro/smartmicro_ros2_radars#38]
I have an issue which seems similar to https://github.com/smartmicro/smartmicro_ros2_radars/issues/20

I have a DRVEGRD 152 (UMRR9D) connected by ethernet (device on 192.168.11.11, host on 192.168.11.17), and I'm able to vizualize data and targets with DriveRecorder.

My `radar.template.yaml` is 
````
---
/**:
  ros__parameters:
    # The client_id to be set in smart_access_config.json, must be a unique integer.
      master_client_id: 1000
      # This sets the dev_id in the hw_inventory.json
      hw_dev_id: 2
      # This sets the port in the hw_inventory.json
      hw_port: 55555
      # This sets the iface_name in the hw_inventory.json
      hw_iface_name: "eth0"
      # An array of sensors to subscribe to.
      sensors:
          # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
          # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
          sensor_0:
              # The model of the connected sensor. Available models umrr11, umrr9d, umrr96,
              # umrr9f_v1_1_1, umrr9f_v2_0_0
              model: "umrr9d"
              # The client_id of the sensor/source, must be a unique integer.
              id: 100
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.11"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
````

I also upgraded the firmware to the last version from support (2.5.0) following https://github.com/smartmicro/smartmicro_ros2_radars/issues/15

`ros2 launch umrr_ros2_driver radar.launch.py` works fine and output 
```
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-09-18-12-50-53-955073-laptop-matthieu-15429
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [smartmicro_radar_node_exe-1]: process started with pid [15439]
[smartmicro_radar_node_exe-1] 1695041453.996041 [0] smartmicro: config: //CycloneDDS/Domain/General: 'NetworkInterfaceAddress': deprecated element (file:///etc/ros_config/cyclonedds.xml line 5)
[smartmicro_radar_node_exe-1] [INFO] [1695041454.005857409] [smart_radar]: Data stream services have been received!
[smartmicro_radar_node_exe-1] [INFO] [1695041456.011675051] [smart_radar]: Radar services are ready.
```

However my topic `/smart_radar/targets_0`  remains empty.

My wireshark log looks like
````
1	0.000000	192.168.11.11	192.168.11.17	UDP	444	55555 → 55555 Len=402
2	0.000000	192.168.11.11	192.168.11.17	UDP	164	55555 → 55555 Len=122
3	0.004519	192.168.11.11	192.168.11.17	UDP	151	1234 → 55555 Len=109
4	0.044726	192.168.11.11	192.168.11.17	UDP	213	1234 → 55555 Len=171
5	0.149958	192.168.11.11	192.168.11.17	UDP	444	55555 → 55555 Len=402
6	0.149958	192.168.11.11	192.168.11.17	UDP	164	55555 → 55555 Len=122
7	0.154395	192.168.11.11	192.168.11.17	UDP	151	1234 → 55555 Len=109
8	0.194453	192.168.11.11	192.168.11.17	UDP	213	1234 → 55555 Len=171
9	0.299967	192.168.11.11	192.168.11.17	UDP	444	55555 → 55555 Len=402
10	0.299967	192.168.11.11	192.168.11.17	UDP	164	55555 → 55555 Len=122
11	0.304394	192.168.11.11	192.168.11.17	UDP	151	1234 → 55555 Len=109
12	0.344424	192.168.11.11	192.168.11.17	UDP	213	1234 → 55555 Len=171
13	0.450206	192.168.11.11	192.168.11.17	UDP	444	55555 → 55555 Len=402
14	0.450206	192.168.11.11	192.168.11.17	UDP	164	55555 → 55555 Len=122
````
Don't know why I received frames from 1234 port by the way

Any help would be appreciated :)
