### ISSUE TITLE
DRVEGRD 171 param file causing runtime error - at least one adapter must be configured

### ISSUE THREAD

**Issue by triton-epark** [smartmicro/smartmicro_ros2_radars#54]
Am running the umrr_ros2_driver with the DRVEGRD 171. As far as I can tell by comparing with the existing parameter yaml files, I have the adapter params written correctly, but am getting runtime errors. What's missing or incorrect?

My params:
```
/smart_radar:
  ros__parameters:
    adapters:
      adapter_0:
        hw_dev_id: 1
        hw_iface_name: "can0"
        hw_type: "can"
        baudrate: 500000
    master_data_serial_type: can_based
    master_inst_serial_type: can_based
    sensors:
      sensor_0:
        link_type: "can"
        pub_type: "target"
        model: "umrra4_can_v1_0_1"
        dev_id: 1
        id: 101
        frame_id: "umrr"
        history_size: 10
        uifname: "umrra4_t171_automotive"
        uifmajorv: 1
        uifminorv: 0
        uifpatchv: 1
```
And get the resulting runtime error:
```
[smartmicro_radar_node_exe-1] [INFO] [1727365282.366125793] [smart_radar]: Updating ADAPTER params.
[smartmicro_radar_node_exe-1] terminate called after throwing an instance of 'std::runtime_error'
[smartmicro_radar_node_exe-1]   what():  At least one adapter must be configured.
```
Thanks.
