### ISSUE TITLE
DRVEGRD 171 CAN runtime error - initialization failed

### ISSUE THREAD

**Issue by triton-epark** [smartmicro/smartmicro_ros2_radars#56]
I can see the can0 interface show up on Ubuntu, I run `sudo ip link set can0 up type can bitrate 500000` and then a candump shows data coming through.

However when I try to run the radar.launch.py launch file in the umrr_ros2_driver, I get the "Initialization failed" runtime error, which based on the code seems to be a communication failure with the sensor?

I'm not sure how that's happening considering I can see and dump the can interface.

Parameter yaml file for context:
```
/smart_radar:
  ros__parameters:
    adapters:
      adapter_0:
        hw_dev_id: 2
        hw_iface_name: "can0"
        hw_type: "can"
        baudrate: 500000
    master_data_serial_type: can_based
    master_inst_serial_type: can_based
    sensors:
      # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
      # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
      # 
      # Sensor `model` names if using link type:
      # can: 'umrr9f_can_mse_v1_0_0', 'umrra4_can_v1_0_1', 'umrr96_can_v1_2_2', 'umrr11_can_v1_1_2', 'umrr9d_can_v1_0_3', 'umrr9d_can_v1_2_2', 'umrr9f_can_v2_1_1', 'umrr9f_can_v2_2_1'
      # port: 'umrr9f_mse_v1_0_0', 'umrra4_v1_0_1', 'umrr96_v1_2_2', 'umrr11_v1_1_2', 'umrr9d_v1_0_3', 'umrr9d_v1_2_2', 'umrr9f_v1_1_1', 'umrr9f_v2_1_1', 'umrr9f_v2_2_1'
      sensor_0:
        # The link of the sensor either 'can' or 'eth'
        link_type: "can"
        # The model of the connected sensor.
        model: "umrra4_can_v1_2_1"
        # Adapter id to which sensor is connected
        dev_id: 2
        # The client_id of the sensor/source, must be a unique integer.
        id: 101
        # The frame_id to be set to the published messages.
        frame_id: "umrr"
        # Specify the history size.
        history_size: 10
        # The interface name of the sensor
        uifname: "umrra4_t171_automotive"
        # The major version of the interface
        uifmajorv: 1
        # The minor version of the interface
        uifminorv: 2
        # The pathc version of the interface
        uifpatchv: 1
```

I have also tried with the sensor model set to "umrra4_can_v1_0_1" and the uifmajorv/minorv/patchv changed accordingly, still the same error.
