### ISSUE TITLE
Sparse target list on DRVEGRD 169

### ISSUE THREAD

**Issue by krzmancd** [smartmicro/smartmicro_ros2_radars#57]
When running the ROS2 driver, our DRVEGRD 169 returns quite a sparse and incoherent target list. See gif bellow.

![radar-gif](https://github.com/user-attachments/assets/9fa89334-f28b-407c-a18f-5faa13e7c884)

I was expecting a more dense point cloud, that would make more sense. Currently, points are hoping in and out of existence. It's hard to determine objects with confidence on the PCL. Is the problem the fact that I'm testing this indoors with lots of chairs, tables and walls? Is it something to do with objects vs targets? What are they?

My config file is as follows: 

```
/**:
  ros__parameters:
    master_inst_serial_type: "can"
    master_data_serial_type: "can"
    adapters:
      adapter_0:
        hw_type: "can"
        hw_dev_id: 2
        hw_iface_name: "can0"
        baudrate: 500000
sensors:
      sensor_0:
        link_type: "can"
        pub_type: "target"
        model: "umrr9f_can_v2_2_1"
        id: 500
        dev_id: 2
        uifname: "umrr9f_t169_automotive"
        uifmajorv: 2
        uifminorv: 2
        uifpatchv: 1
        frame_id: "umrr"
        history_size: 10
```

Just in case it's needed, I'm also providing `hw_inventory.json` and `routing_table.json`

```
{"hwItems":[{"baudrate":500000,"dev_id":2,"iface_name":"can0","port":55555,"type":"can"}],"name":"HW Inventory List","version":"1.1.0"}
```

```
{
    "clients": [
        {
            "can_network_id": 0,
            "client_id": 500,
            "data_serialization_type": "",
            "dev_id": 2,
            "instruction_serialization_type": "",
            "ip": "",
            "link_type": "can",
            "port": 0,
            "user_interface_major_v": 2,
            "user_interface_minor_v": 4,
            "user_interface_name": "umrr9f_t169_automotive",
            "user_interface_patch_v": 1
        }
    ],
    "name": "Client Routing Table",
    "version": "1.0.0"
}
```

Thank you for your help!
