### ISSUE TITLE
Cannot receive data from DRVEGRD 169 via CAN using ROS 2 driver, despite correct CAN signal

### ISSUE THREAD

**Issue by vanbla2** [smartmicro/smartmicro_ros2_radars#63]
We are currently integrating two Smartmicro radar sensors in a ROS 2 environment via CAN bus. Both are connected to can0 and CAN communication is functioning properly, as verified with candump.

While we are able to correctly read data from the DRVEGRD 152 model, the DRVEGRD 169 sensor does not produce any readable data through the ROS 2 driver, even though the CAN interface is active and transmitting.

Below is the relevant section of our configuration:

```
ros__parameters:
  adapters:
    adapter_0: # can0 for Smartmicro 169 - Rear Left
      hw_dev_id: 11
      hw_iface_name: "can0"
      hw_type: "can"
      baudrate: 500000
  sensors:
    sensor_0: # Smartmicro 169 - Rear Left
      link_type: "can"
      pub_type: "target"
      model: "umrr9f_can_v2_2_1" 
      dev_id: 11
      id: 400
      frame_id: "radar_sensor_rear_left"
      history_size: 10
      inst_type: "port_based"
      data_type: "port_based"
      uifname: "umrr9f_t169_automotive"  
      uifmajorv: 2
      uifminorv: 2
      uifpatchv: 1
```

Questions:

    Is the model field (umrr9f_can_v2_2_1) appropriate for the DRVEGRD 169 sensor?

    Is the uifname value (umrr9d_t152_automotive) correct for this sensor, or should it be different?

    Are there any additional parameters or adjustments needed specifically for DRVEGRD 169 compatibility?

Any suggestions or clarifications would be greatly appreciated.

Thanks in advance for your support!

**Comment by smartSRA** [comment]
Hey,

I see that the some of the params are missing:

```
ros__parameters:
  master_data_serial_type: can_based
  master_inst_serial_type: can_based
  adapters:
    adapter_0: # can0 for Smartmicro 169 - Rear Left
      hw_dev_id: 11
      hw_iface_name: "can0"
      hw_type: "can"
      baudrate: 500000
  sensors:
    sensor_0: # Smartmicro 169 - Rear Left
      link_type: "can"
      pub_type: "target"
      model: "umrr9f_can_v2_2_1" 
      dev_id: 11
      id: 400
      frame_id: "radar_sensor_rear_left"
      history_size: 10
      inst_type: "can_based"
      data_type: "can_based"
      uifname: "umrr9f_t169_automotive"  
      uifmajorv: 2
      uifminorv: 2
      uifpatchv: 1

```


Can you try it out with the above configurations and let me know if it is resolved?
